

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {store} from "../app/store/store"
import Providers from "./providers/sessionProvider";
import NextAuthSessionProvider from "./providers/sessionProvider";
import SessionProvider from './components/SessionProvider';
import { getServerSession } from "next-auth";
// import {SessionProvider} from "next-auth/react";
import Layout from './components/Layout';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}> 
      {/* <NextAuthSessionProvider > */}
      <SessionProvider session={session}>
      <Providers >
      <Layout>
      {children}
      </Layout>
      </Providers>

      </SessionProvider>
      {/* </NextAuthSessionProvider> */}
      </body>
    </html>
  )
}
