name: Deploy Next.js

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
        
      - name: Build Next.js project
        run: npm run build
        
      - name: Deploy to production
        run: npm start
